# Generated by Django 4.2.7 on 2024-02-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='articles', to='category.category', verbose_name='Category'),
        ),
    ]
