# Generated by Django 4.2.7 on 2024-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('article', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(db_index=True, related_name='articles', to='tag.tag', verbose_name='Tag'),
        ),
    ]
